# GitLeaks configuration for dotfiles repository
# Scans for secrets, API keys, and sensitive information

title = "Dotfiles Security Scan"

[extend]
# Use default gitleaks rules
useDefault = true

[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(api[_-]?key|apikey)['"]*\s*[:=]\s*['"][a-zA-Z0-9]{16,}['"]'''
tags = ["key", "API"]

[[rules]]
description = "AWS Access Key"
id = "aws-access-key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["key", "AWS"]

[[rules]]
description = "GitHub Token"
id = "github-token"
regex = '''gh[pousr]_[A-Za-z0-9_]{36,255}'''
tags = ["key", "GitHub"]

[[rules]]
description = "Anthropic API Key"
id = "anthropic-api-key"
regex = '''sk-ant-api03-[a-zA-Z0-9\-_]{95}'''
tags = ["key", "Anthropic"]

[[rules]]
description = "Private SSH Key"
id = "ssh-private-key"
regex = '''-----BEGIN (?:RSA |OPENSSH |DSA |EC |PGP )?PRIVATE KEY-----'''
tags = ["key", "SSH"]

# Allowlist for known safe patterns
[[rules.allowlist]]
description = "Ignore example keys in documentation"
regexes = [
    '''sk-ant-api03-example''',
    '''EXAMPLE_API_KEY''',
    '''your-api-key-here''',
    '''<your-.*-key>''',
]

[[rules.allowlist]]
description = "Ignore bitwarden CLI examples"
regexes = [
    '''bw get password.*API Key''',
    '''\$\(bw get password''',
]

# File paths to ignore
[allowlist]
paths = [
    '''.*\.git/.*''',
    '''.*node_modules/.*''',
    '''.*\.log$''',
    '''.*\.cache/.*''',
]
