# GitLeaks configuration for config repo
title = "Config Repo Security Scan"

[extend]
# Use default rules
useDefault = true

[[rules]]
description = "Anthropic API Key"
id = "anthropic-api-key"
regex = '''sk-ant-api\d{2}-[A-Za-z0-9_-]{95}'''
tags = ["key", "anthropic"]

[[rules]]
description = "OpenAI API Key"
id = "openai-api-key"
regex = '''sk-[A-Za-z0-9]{48}'''
tags = ["key", "openai"]

[[rules]]
description = "Google API Key"
id = "google-api-key"
regex = '''AIza[0-9A-Za-z_-]{35}'''
tags = ["key", "google"]

[[rules]]
description = "Tavily API Key"
id = "tavily-api-key"
regex = '''tvly-[A-Za-z0-9]{32}'''
tags = ["key", "tavily"]

# Allowlist for false positives
[allowlist]
description = "Example API keys in documentation"
paths = [
    '''.*README\.md''',
    '''.*\.md''',
]
regexes = [
    '''your-api-key''',
    '''your-actual-api-key''',
    '''sk-ant-api03-example''',
]