# Nushell Configuration - Minimal Setup

# Basic shell behavior
$env.config = {
    show_banner: false
    edit_mode: emacs
    buffer_editor: "nvim"
    cursor_shape: {
        emacs: line
        vi_insert: line 
        vi_normal: block
    }
    use_ansi_coloring: true
    bracketed_paste: true
    render_right_prompt_on_last_line: false
    shell_integration: {
        osc2: true
        osc7: true
        osc8: true
        osc9_9: false
        osc133: false  # Disable OSC 133 to fix WezTerm scrolling issue on Windows
        osc633: true
        reset_application_mode: true
    }
    table: {
        mode: rounded
        index_mode: always
        show_empty: true
        padding: { left: 1, right: 1 }
        trim: {
            methodology: wrapping
            wrapping_try_keep_words: true
        }
    }
    completions: {
        case_sensitive: false
        quick: true
        partial: true
        algorithm: "fuzzy"
    }
}

# Initialize mise (generated by env-linux.nu on startup)
source ~/.config/nushell/mise.nu

# Initialize Starship prompt if available
if ("~/.cache/starship/init.nu" | path exists) {
    use ~/.cache/starship/init.nu
}

# Initialize Zoxide
source ~/.zoxide.nu

# Load Windows-specific configuration
if $nu.os-info.name == "windows" {
    try {
        source config-windows.nu
    }
}

# Load WSL-specific configuration
if $nu.os-info.name == "linux" {
    if ("/proc/version" | path exists) {
        let proc_version = (open /proc/version)
        if ($proc_version | str contains "WSL") or ($proc_version | str contains "microsoft") {
            try {
                source wsl-config.nu
            } catch { |e|
                print $"Warning: Failed to load wsl-config.nu: ($e)"
            }
        }
    }
}

# Shell integrations
source ~/.config/nushell/vendor/autoload/wt.nu

# Aliases
alias claude = claude --dangerously-skip-permissions

# Custom Commands

# Run gvisor-isolated dev container
def gvisor-dev [] {
    let script = ( $nu.default-config-dir | path join ".." "gvisor-dev" "run.sh" | into string)
    if ($script | path exists) {
        nu $script
    } else if ("~/repos/configs/gvisor-dev/run.sh" | path exists) {
        nu ~/repos/configs/gvisor-dev/run.sh
    } else {
        print $"Error: gvisor-dev script not found at: ($script)"
    }
}

# Attach to running dev container with fzf
def gvisor-attach [] {
    let selected = (^bash -c "docker ps --filter 'name=dev-' --format '{{.Names}}' | fzf" | str trim)
    if not ($selected | is-empty) {
        docker exec -it $selected nu
    }
}

# Pull and run the qwen2.5-coder model in Ollama
def ollama-run [] {
    ollama pull qwen2.5-coder:7b
    ollama run qwen2.5-coder:7b
}




use ($nu.default-config-dir | path join mise.nu)