# Nushell Configuration - Minimal Setup

# Basic shell behavior
$env.config = {
    show_banner: false
    edit_mode: emacs
    buffer_editor: "nvim"
    cursor_shape: {
        emacs: line
        vi_insert: line 
        vi_normal: block
    }
    use_ansi_coloring: true
    bracketed_paste: false
    render_right_prompt_on_last_line: false
    shell_integration: {
        osc2: true
        osc7: true
        osc8: true
        osc9_9: false
        # Semantic prompt marks (133;A/B/C/D). Nushell defaults this to true.
        # It was off here to dodge a WezTerm buffer-scroll-on-keypress bug, but
        # that one is Windows/conpty-only (wezterm#5859, nushell#5585) and this
        # config runs on macOS. Off also disabled click-to-cursor, which
        # reedline gates on the same flag.
        #
        # tmux consumes the marks itself to power copy-mode next-prompt /
        # previous-prompt; see tmux/tmux.conf.
        osc133: true
        osc633: true
        reset_application_mode: true
    }
    table: {
        mode: rounded
        index_mode: always
        show_empty: true
        padding: { left: 1, right: 1 }
        trim: {
            methodology: wrapping
            wrapping_try_keep_words: true
        }
    }
    completions: {
        case_sensitive: false
        quick: true
        partial: true
        algorithm: "fuzzy"
    }
}

# Initialize mise (generated by env-linux.nu on startup)
source ~/.config/nushell/mise.nu

# Initialize Starship prompt if available
if ("~/.cache/starship/init.nu" | path exists) {
    use ~/.cache/starship/init.nu
}

# Initialize Zoxide
source ~/.zoxide.nu

# Initialize Atuin (init.nu generated by env.nu on startup)
if ("~/.local/share/atuin/init.nu" | path exists) {
    source ~/.local/share/atuin/init.nu
}

# Load Windows-specific configuration
if $nu.os-info.name == "windows" {
    try {
        source config-windows.nu
    }
}

# Load WSL-specific configuration
if $nu.os-info.name == "linux" {
    if ("/proc/version" | path exists) {
        let proc_version = (open /proc/version)
        if ($proc_version | str contains "WSL") or ($proc_version | str contains "microsoft") {
            try {
                source wsl-config.nu
            } catch { |e|
                print $"Warning: Failed to load wsl-config.nu: ($e)"
            }
        }
    }
}

# Aliases
# --tools trims the built-in tool schemas out of the context window.
# Dropped: Artifact, SendUserFile, ReportFindings, ScheduleWakeup, SendFeedback, AskUserQuestion.
# No settings.json equivalent exists; --tools is CLI-only.
# This is an alias, so it only applies to claude started from an interactive
# nushell. Agents that workmux launches run under the sandbox container's dash
# and never see it, so the same list is duplicated in workmux/config.yaml under
# `agents.cc-sandbox.args`. Change one, change the other.
alias claude = claude --dangerously-skip-permissions --tools "Bash,Read,Edit,Write,Agent,Skill,ToolSearch,ListAgents,NotebookEdit,WebFetch,WebSearch"

# Custom Commands

# Run gvisor-isolated dev container
def gvisor-dev [] {
    let script = ( $nu.default-config-dir | path join ".." "gvisor-dev" "run.sh" | into string)
    if ($script | path exists) {
        nu $script
    } else if ("~/repos/configs/gvisor-dev/run.sh" | path exists) {
        nu ~/repos/configs/gvisor-dev/run.sh
    } else {
        print $"Error: gvisor-dev script not found at: ($script)"
    }
}

# Attach to running dev container with fzf
def gvisor-attach [] {
    let selected = (^bash -c "docker ps --filter 'name=dev-' --format '{{.Names}}' | fzf" | str trim)
    if not ($selected | is-empty) {
        docker exec -it $selected nu
    }
}

# Pull and run the qwen2.5-coder model in Ollama
def ollama-run [] {
    ollama pull qwen2.5-coder:7b
    ollama run qwen2.5-coder:7b
}

# Hosts the workmux sandbox proxy refused, for filling in
# workmux/config.yaml sandbox.network.allowed_domains.
#
# Sorted by most recent, and `last` is the column that matters: the log is
# append-only and never pruned, so a host fixed weeks ago still shows its old
# rejections forever. High `hits` with an old `last` means already allowlisted.
# Anything from the last few minutes is a real gap.
#
# --hours limits the window, for when you want only what a run you just did
# produced.
def wm-rejects [--hours: int] {
    let log = ("~/.local/state/workmux/workmux.log" | path expand)
    if not ($log | path exists) {
        print $"no workmux proxy log at ($log)"
        return
    }

    let rows = (
        open $log
        | lines
        | where $it =~ "rejected: domain not in allowlist"
        | parse -r '(?<time>\S+)\s+WARN rejected.*hostname="(?<host>[^"]+)"'
        | insert when {|r| $r.time | into datetime }
    )

    let rows = if $hours == null {
        $rows
    } else {
        $rows | where when > ((date now) - ($hours * 1hr))
    }

    $rows
    | group-by host
    | items {|host, hits|
        let last = ($hits | get when | math max)
        # `last` stays a datetime rather than a formatted string so nu renders
        # it as "4 minutes ago" and sort-by below still orders correctly.
        {
            host: $host
            hits: ($hits | length)
            last: $last
        }
    }
    | sort-by last -r
}




# mise.nu already sourced above - do not use/source again