# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
- name: Install docker and containerd
  hosts: '*'
  gather_facts: true
  tasks:
    - name: install dependencies
      become: true
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
      loop:
        - nfs-common
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - apt-transport-https
        - zsh
        - zoxide

    - name: create repo folder
      file:
        path: ~/repos 
        state: directory
        mode: u+rwx

    - name: create repo folder
      file:
        path: ~/.zsh
        state: directory
        mode: u+rwx

    - name: create zsh-plugins folders
      file:
        path: '~/.zsh/{{ item }}' 
        state: directory
        mode: u+rwx
      loop:
          - 'zsh-autosuggestions'
          - 'zsh-completions'
          - 'zsh-syntax-highlighting'


    - name: install zsh plugins
      git:
        repo: 'https://github.com/zsh-users/{{ item }}.git' 
        dest: '~/.zsh/{{ item }}'
        depth: 1
      loop:
        - zsh-autosuggestions
        - zsh-completions
        - zsh-syntax-highlighting

    - name: change default shell
      become: true
      shell: chsh -s /bin/zsh

    - name: copy neovim config
      copy:
        src: ../nvim/
        dest: ~/.config/nvim/

    - name: copy bashrc
      copy:
        src: ../bash/.bashrc
        dest: ~/.bashrc

    - name: copy zshrc
      copy:
        src: ../zsh/.zshrc
        dest: ~/.zshrc

   - community.general.homebrew:
        name: '{{ item }}'
        state: present
      loop:
        - kubectx
        - starship
        
